class workstation::common {
  exec { 'enable ntp':
    command  =>  '/usr/bin/timedatectl set-ntp true',
    onlyif   =>  '/usr/bin/timedatectl status | grep NTP | grep -q no'
  }
  file { '/etc/pacman.d/mirrorlist':
    source  =>  'puppet:///modules/workstation/etc-pacman_d-mirrorlist',
    notify  =>  Exec['pacman update']
  }
  file { '/etc/pacman.conf':
    source  =>  'puppet:///modules/workstation/etc-pacman_conf',
    notify  =>  Exec['pacman update']
  }
  exec { 'pacman update':
    command =>  '/usr/bin/pacman -Syu --noconfirm --noprogressbar --force',
    user    =>  'root',
    refreshonly => true
  }
  $packages = [
    'autoconf',
    'automake',
    'binutils',
    'file',
    'findutils',
    'flex',
    'gawk',
    'gettext',
    'groff',
    'gzip',
    'libtool',
    'make',
    'pkg-config',
    'sudo',
    'texinfo',
    'util-linux',
    'which',
    'htop',
    'iotop',
    'vnstat',
    'iftop',
    'git',
    'xz',
    'nano',
    'docker',
    'openvpn',
    'openssh',
    'irssi',
    'screen',
    'tmux',
    'wget',
    'curl',
    'python',
    'ruby',
    'gcc-go',
    'rsync',
    'borg',
    'ncurses',
    'jre8-openjdk',
    'jdk8-openjdk',
    'imagemagick',
    'samba',
    'smbclient',
    'openssl',
    'rsnapshot',
    'gnupg',
    'fuse2',
    'logrotate',
    'man-pages',
    'acpid',
    'unrar',
    'zip',
    'unzip',
    'diffutils',
    'at',
    'fcgi',
    'dhcpcd',
    'ark',
    'wireshark-cli',
    'wpa_supplicant',
    'python-requests',
    'mercurial',
    'coreutils',
    'whois',
    'readline',
    'gnutls',
    'mutt',
    'vim',
    'vim-runtime',
    'linux-firmware',
    'mc',
    'ipmitool',
    'hdparm',
    'smartmontools',
    'ncdu',
    'dkms',
    'tar',
    'tcpdump',
    'gcc',
    'rtorrent',
    'fakeroot',
    'sed',
    'grep',
    'm4',
    'dosfstools',
    'ntfs-3g',
    'mdadm',
    'vi',
    'lsof',
    'patch',
    'lzo',
    'java-environment-common',
    'java-runtime-common',
    'imake',
    'acpi',
    'bzip2',
    'rfkill',
    'pm-utils',
  ]
  package { $packages:
    ensure   =>  installed,
    provider =>  'pacman'
  }
  Package {
    require   =>  [ Exec['pacman update'], File['/etc/pacman.conf'], File['/etc/pacman.d/mirrorlist'] ]
  }
}
